### ISSUE TITLE
Additional resolver is not working on jest

### ISSUE THREAD

**Issue by evrenesat** [timarney/react-app-rewired#141] opened 2017-11-15 08:27 UTC
Hello,

Thank you for this project. I'm using the following config override to be able to import packages outside of project folder. But jest could not find the package that I'm loading from that path. Is that normal, should I also provide the same resolver to jest via `resolver` config?

react@15.6.1 
react-app-rewired@1.3.5

config-overrides.js
```javascript
const path = require('path');
const fs = require('fs');

const appDirectory = fs.realpathSync(process.cwd());
const resolveRelativePath = relativePath => path.resolve(appDirectory, relativePath);
const extlibPath = resolveRelativePath('../../../../extlib/js');
const extlibBabelConfig = {
  test: /\.(js|jsx)$/,
  include: extlibPath,
  loader: require.resolve('babel-loader'),
  options: {
    babelrc: false,
    presets: [require.resolve('babel-preset-react-app')],
    compact: true
  }
};
module.exports = function override (config, env) {
  // allow importing from outside of app/src folder, ModuleScopePlugin prevents this.
  delete config.resolve.plugins.ModuleScopePlugin;
  // add extlib/js path to resolve path list,
  // so we can import from extlib without relative path dots (../../..), just like node_modules
  config.resolve.modules.push(extlibPath);
  // treat the modules that placed under extlib as ES6
  config.module.rules.push(extlibBabelConfig);
  return config;
};
```

Error:
```bash
 FAIL  src\containers\App.test.js
  ● Test suite failed to run

    Cannot find module 'number-format/NumberFormat' from 'Parameter.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/components/Parameter.js:3:21)
```

**Comment by timarney** [comment] 2017-11-25 13:10
I won't have time to dig into this but did you try providing the config to Jest?


```module.exports = {
  webpack: function (config, env) {
    return config;
  },
  jest: function (config) {
    return config;
  }

```

See 
```
https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/config-overrides.js
```

**Comment by timarney** [comment] 2017-11-28 07:23
Going to close this as it's not bug related.

This has been opened to cover Jest related notes https://github.com/timarney/react-app-rewired/issues/146.  If you do happen to figure it out might be worth noting.

**Closed by timarney** 2017-11-28 07:23 UTC

**Comment by stephenkoo** [comment] 2018-06-14 05:11
@timarney I'm having the same difficulty finding a way to add `require.resolve('babel-loader')` into Jest config, since it's structured differently from the webpack config.

For context, I'm following https://www.youtube.com/watch?v=gt8x6uODvEQ / and successfully performing the webpack part of the `config-override.js`, but Jest (due to the config being different) doesn't like this:
```

module.exports = {
  webpack: function override(config, env) {
    config.module.rules[1].oneOf[2].use.unshift({
      loader: require.resolve('babel-loader'),
    });

    return config;
  },
  jest: function override(config) {
      config.module.rules[1].oneOf[2].use.unshift({
        loader: require.resolve('babel-loader'),
      });

    return config;
  },
};

```

This results in babel-plugin-emotion not being loaded into Jest tests.

**Comment by timarney** [comment] 2018-06-14 10:48
@stephenkoo

Have you seen 
https://github.com/osdevisnot/react-app-rewire-contrib/tree/master/packages/react-app-rewire-emotion ?

**Comment by dawnmist** [comment] 2018-06-14 12:08
@stephenkoo Jest doesn't use Webpack at all, so trying to modify Webpack rules for it will not work. The config it is editing is a [Jest Config](https://facebook.github.io/jest/docs/en/configuration.html). There _are_ no loaders to modify for the Jest config, as it doesn't use Webpack loaders. Assuming that you've used create-react-app-typescript, the `yarn test` script will invoke jest using ts-jest to transpile.

Setting up your jest function is [documented here](https://github.com/timarney/react-app-rewired#2-jest-configuration---testing).

The default Jest config given to your config-overrides jest function permits you to specify babel plugins through either .babelrc or in a babel section in your package.json file using the _normal babel configuration options_. If all you need to do for the Jest testing is to add babel plugins, you don't even _need_ to specify the jest function - just create your babel configuration and it'll be automatically used.

As an example, I have a project (also in typescript) where I use dynamic imports for code splitting. Node doesn't understand their syntax by default, so I need to use babel-plugin-dynamic-import-node. I wanted to restrict this to the testing environment only, as webpack's loaders handle it automatically. I also needed to transform some modules from es2015 to commonjs so that node would understand them. To do this, _all_ that was required was to add the following section to my package.json file:
```json
{
  ...,
  "babel": {
    "env": {
      "test": {
        "plugins": [
          "transform-es2015-modules-commonjs",
          "dynamic-import-node"
        ]
      }
    }
  }
}
```

**Comment by stephenkoo** [comment] 2018-06-14 12:31
@dawnmist Thanks - I gave it a shot, but it's not working for `babel-plugin-emotion` (Same errors.)
What I did:

1. Delete `.babelrc`
2. Delete `configure-override.json`
3. Add this to the end of `package.json` as per your example + babel-plugin-emotion documentation:

```json
  "babel": {
    "env": {
      "production": {
        "plugins": [["emotion", { "hoist": true }]]
      },
      "development": {
        "plugins": [["emotion",  { "sourceMap": true, "autoLabel": true }]]
      },
      "test": {
        "plugins": [["emotion",  { "hoist": true }]]
      }
    }
  }
```

Result: Both `yarn start` & `yarn test` result in error not recognizing babel-plugin-emotion being installed.

**Comment by dawnmist** [comment] 2018-06-14 12:46
@stephenkoo Have you got an example repo that I can take a look at?

**Comment by stephenkoo** [comment] 2018-06-14 12:51
@dawnmist Definitely! https://gitlab.com/stephenkoo/kanso/tree/custom-setup

**Comment by dawnmist** [comment] 2018-06-14 13:50
@stephenkoo I'm still tracing through what ts-jest/babel are doing with the test, but I [found this bug report](https://github.com/emotion-js/emotion/issues/687) while looking up details about babel-plugin-emotion. I suspect that it may be related, but simply changing the module type to compile to doesn't fix it. Their sample repo may help though, as they have a "working" and "not working" example to trace through.

**Comment by dawnmist** [comment] 2018-06-14 14:46
@stephenkoo This syntax in App.tsx works with no other changes to your sample project:
```js
const StyledDiv = styled('div')`
  color: pink;
  flex: 1;
`;
```
Not sure whether you're happy to switch to using it, but it is a relatively minor change (from `styled.div` to `styled('div')`) that can save you a lot of headaches.

**Comment by stephenkoo** [comment] 2018-06-15 00:29
@dawnmist Ah, yes - thanks for finding the root cause of the issue! I thought it must've been me not setting rewired up properly.

You’re right - `babel-plugin-emotion` is not necessary for emotion to work, but it provides optimization benefits that I'd rather not do without - the syntax I used was just to test if `babel-plugin-emotion` works with Create React App & TypeScript using rewired.

Sadly it looks like I'll have to choose either TypeScript or the optimisation benefits of the emotion plugin due to the issue you linked to.
