### ISSUE TITLE
overriding publicPath example

### ISSUE THREAD

**Issue by JackLeo** [timarney/react-app-rewired#297] opened 2018-08-23 15:24 UTC
I have an override:
```js
module.exports = {
  devServer: function(configFunction) {
    return function(proxy, allowedHost) {
      const config = configFunction(proxy, allowedHost);
      config.publicPath = '/conversation/';
      return config;
    }
  }
}
```
But when running this bundle link remains the same, yet it succeeds returning the ingex page again rather than js

What should be the correct way of overriding this parameter?

**Comment by JackLeo** [comment] 2018-08-23 15:33
Ah it was because I did not navigate to `/conversation/` it still does not work as it loads so I'm going to edit the issue

**Comment by timarney** [comment] 2018-09-01 17:31
Likely both of these are need to be set.
```
const publicUrl = paths.publicUrl;
const publicPath = config.output.publicPath;
```
https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/scripts/build.js#L111

Closing this as it's not a bug.

**Closed by timarney** 2018-09-01 17:31 UTC
