### ISSUE TITLE
How to package html js css separately in different directories, how should I configure？

### ISSUE THREAD

**Issue by wiiler** [timarney/react-app-rewired#390] opened 2019-04-24 12:25 UTC
How to package html js css separately in different directories, how should I configure？

**Comment by dawnmist** [comment] 2019-04-25 20:20
Separately how?

Currently CRA packages things as:
* build/
  * index.html
  * favicon.ico
  * asset-manifest.json
  * manifest.json
  * preload.js
  * service-worker.js
  * static/
    * css/
      * css bundles for your javascript bundles (often just a main.xyz.chunk.css)
    * js/
      * your various javascript bundles
    * media/
      * your linked images

What did you want to change?

**Comment by timarney** [comment] 2019-05-02 09:43
Closing this.  

Not a bug.

**Closed by timarney** 2019-05-02 09:43 UTC
