### ISSUE TITLE
using .babelrc appears to blow away jest configuration

### ISSUE THREAD

**Issue by dmk255** [timarney/react-app-rewired#192] opened 2018-01-20 14:48 UTC
Hello!

I might be misinterpreting the documentation so I thought I'd post here. I'm interested in using the babel plugin https://github.com/speedskater/babel-plugin-rewire to be able to test my private functions.

I have added a .babelrc with the following content:
```JSON
{
    "plugins": ["rewire"]
}
```

Although the plugin does take affect, it appears that any settings config-overrides under the `jest` key no longer take affect. 

For example, I am now receiving errors that my import syntax (e.g. `import foo from './foo'`) is no longer working. Additionally, I am not able to import my installed modules (e.g. `import thunk from 'redux-thunk'`)

Is there a way to add a babel plugin to the jest configuration without blowing away all the settings in config-overrides?

**Comment by timarney** [comment] 2018-01-24 18:22
@dawnmist any thoughts on this? Your more tuned in on the Jest end of things.

**Comment by dawnmist** [comment] 2018-01-25 05:27
Can you make an example project that reproduces the issue that I can use to debug?

At the moment I am successfully using one babel plugin (which was only needed in test mode) with config-overrides making changes in jest - I have defined it inside package.json:
```json
"babel": {
    "env": {
      "test": {
        "plugins": [
          "dynamic-import-node"
        ]
      }
    }
  }
```

**Comment by dmk255** [comment] 2018-01-25 15:16
@dawnmist Sure! I might not be able to get it to you till tomorrow but I'll make a reproducible repo.

**Comment by dmk255** [comment] 2018-01-30 14:10
Sorry for the delay. Just wanted to post that I'll be working on this tonight

**Comment by dmk255** [comment] 2018-02-14 05:33
@dawnmist Sorry for the delay - I've created an example repository show casing the error.

reproduction steps are in the README.md. This is pretty much a clean CRA install with the addition of rewired and one babel plugin.

https://github.com/dmk255/react-rewired-jest-issue

**Comment by unconfident** [comment] 2018-02-20 10:28
It seems that regardless of whether or not "babel" configuration is present, `react-app-rewired/scripts/utils/babelTransform.js` is never being required despite successful path replacement in `config.transform` object

**Comment by dawnmist** [comment] 2018-02-26 09:39
@dmk255 Sorry it has taken a little while to get to have a look at this. It seems to be something particular to babel-plugin-rewire, since if I replace the plugin with another babel plugin (e.g. "dynamic-import-node"), the application compiles without issue. I figured since the babel-plugin-rewire wasn't actually being used in the example test repository it was safe to test defining different plugins to see if all plugins would trigger the issue, or just the babel-plugin-rewire one. As soon as I add that plugin back into the definition, compiling breaks again.

I'm still looking into whether I can find out why that particular plugin is breaking the babel compile, but I don't think the issue is actually related to react-app-rewired as such.

**Comment by dawnmist** [comment] 2018-02-26 10:20
@dmk255 Ok, this is odd. With the babel-plugin-rewire active, all the non-es6 imports seem to be require the `import * as Name from 'zzz'` instead of `import Name from 'zzz'` syntax. This includes the React, ReactDOM and svg logo, but not your App component.

i.e. Changing the beginning of App.js to:
```javascript
import * as React from 'react';
import * as logo from './logo.svg';
import './App.css';

class App extends React.Component {
```
and changing the beginning of App.test.js to:
```javascript
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import App from './App';
```
allows it to compile properly with the babel-plugin-rewire plugin active.

At this point, I'd suggest asking the people who maintain babel-plugin-rewire whether they can assist with finding out why the normal imports are not working properly when the rewire plugin is active. Feel free to point them to this issue as a starting point, and you should be able to reuse the example repository you provided here as an example for them to look at. I did take a brief look at their readme documentation, but their examples for the plugin's use with React didn't actually show how React needed to be imported so I couldn't confirm whether the above changes were supposed to be required for babel-plugin-rewire to work or not.

**Comment by timarney** [comment] 2018-02-26 10:47
Thanks @dawnmist 

Just for clarification if someone from babel-plugin-rewire is looking here.  This repo originally used https://github.com/jhnns/rewire hence the name but it no longer does.

Rewiring rewires 🙃.

**Comment by timarney** [comment] 2018-03-02 03:37
Closing this as it doesn't appear to be a direct issue of this repo.

**Closed by timarney** 2018-03-02 03:37 UTC
