### ISSUE TITLE
React Navigation web not compatible with react-app-rewired

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [timarney/react-app-rewired#373] opened 2019-03-12 06:43 UTC
```
"dependencies": {
    "@react-navigation/core": "3.0.0-alpha.19",
    "@react-navigation/web": "^1.0.0-alpha",
    "react": "^16.8.4",
    "react-art": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-native-web": "0.10.0",
    "react-scripts": "2.1.8"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "7.3.4",
    "@babel/plugin-proposal-export-default-from": "7.2.0",
    "customize-cra": "0.2.12",
    "react-app-rewired": "2.1.0"
  },
```
React Navigation works when run with `react-scripts start` but fails when scripts is replaced with `react-app-rewired start`

This is `config-overrides.js` file
![image](https://user-images.githubusercontent.com/13464885/54179917-2e238480-44c0-11e9-82d4-11c705470a75.png)

Output
![image](https://user-images.githubusercontent.com/13464885/54179754-b5bcc380-44bf-11e9-9dff-037badeef18c.png)

**Comment by dawnmist** [comment] 2019-03-12 10:56
I'm not sure that react-app-rewired had ever been working with react-native...it was designed for react (create-react-app), and there are a lot of differences between create-react-app and create-react-native-app.

**Comment by SupriyaKalghatgi** [comment] 2019-03-13 03:53
@dawnmist I didn't mention react-native anywhere.
The project I tried was as per the installation procedure mentioned in create-react-app

**Comment by dawnmist** [comment] 2019-03-13 09:24
This [React Navigation: Routing and navigation for your React Native apps](https://reactnavigation.org/)?

The library you specifically mentioned is designed for React Native, the screenshot you added for config-overrides.js contains a ton of react-native paths including an alias for react-native to react-native-web, so my understanding was that you were trying to get things working with the web version of react-native.

You've given very little information about the error itself - it looks like an issue somewhere in babel because the stuff it is complaining about is compiled code. Running with react-scripts on its own won't be including all the babelInclude/addBabelPlugins changes you're adding in your config-overrides.js file, so I'd start looking into whether it is one of the babel includes/plugins that you're adding in config-overrides.js that is causing your issue.

**Comment by SupriyaKalghatgi** [comment] 2019-03-13 14:40
When I exclude `react-navigation/web` from project and run with `react-app-rewired`, it works fine with `config-overrides.js`

**Comment by timarney** [comment] 2019-03-22 16:33
Closing this.

As this isn't a bug.

**Closed by timarney** 2019-03-22 16:33 UTC
