### ISSUE TITLE
Uncaught Error: Iframe has not been created yet.

### ISSUE THREAD

**Issue by mads-thines** [timarney/react-app-rewired#381] opened 2019-04-11 14:30 UTC
On a installation of CRA 2.0, with this installed, hot loading fails.
It loads the file correctly, but when I save the file without any changes, it crashes and prompts me the following error: 

#### [See video for better understanding - https://www.loom.com/share/673390a71fdf411b8885dda1a88a9198](https://www.loom.com/share/673390a71fdf411b8885dda1a88a9198)

I've been trying to install Hot Reloader to fix the issue, but the problem consists. 
Do you guys have any idea what's giving me the problem?

```console
VM6563 0.chunk.js:29568 Uncaught Error: Iframe has not been created yet.
    at me (VM6563 0.chunk.js:29568)
    at Object.window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__.iframeReady (VM6563 0.chunk.js:29578)
    at Module.<anonymous> (<anonymous>:1:280713)
    at n (<anonymous>:1:110)
    at <anonymous>:1:904
    at <anonymous>:1:915
    at HTMLIFrameElement.e.onload (VM6563 0.chunk.js:29560)
```

package.json
```js
{
  "name": "project_title",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --modulePaths=src",
  },
  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "^2.1.8"
  },
  "devDependencies": {
    "@adaptagency/fe_tools": "^1.6.4",
    "@svgr/webpack": "^4.2.0",
    "autoprefixer": "^9.5.1",
    "colors": "^1.3.3",
    "css-loader": "^2.1.1",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.6.0",
    "node-sass": "^4.9.4",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "postcss-calc": "^7.0.1",
    "postcss-flexbugs-fixes": "^4.1.0",
    "postcss-inline-svg": "^3.1.1",
    "postcss-loader": "^3.0.0",
    "prompt": "1.0.0",
    "prop-types": "^15.6.2",
    "react-app-rewire-eslint": "^0.2.3",
    "react-app-rewired": "^2.1.1",
    "release-it": "^10.4.1",
    "sass-loader": "^7.1.0",
    "sass-resources-loader": "^2.0.0",
    "style-loader": "^0.23.1",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "webpack": "^4.29.6",
    "webpack-bundle-analyzer": "^3.3.1",
    "webpack-cli": "^3.3.0",
    "webpack-delete-after-emit": "^1.0.5"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

**Comment by timarney** [comment] 2019-04-26 11:35
Closing this - as I can't support troubleshooting config issues.  If you believe this is a bug please try to create a demo repo that narrows things down.

**Closed by timarney** 2019-04-26 11:35 UTC

**Comment by linlinlinlinzhongniao** [comment] 2019-09-24 08:05
I have the same problem. How did you solve it . thx

**Comment by mthines** [comment] 2019-10-01 13:56
I ended up rewriting the whole config, and the error dissapeared.
You can look at my repo for inspiration: 
https://github.com/adaptdk/react_boilerplate

**Comment by tommyspot** [comment] 2021-11-18 11:14
Hi @mthines,
I am still facing the issue. Could you give me the root cause and how to resolve it?
Thanks!

**Comment by mthines** [comment] 2021-11-18 12:10
@tommyspot 
I ended up switching to nextjs, so couldn't tell, sorry ☺️
