### ISSUE TITLE
How to override getClientEnvironment?

### ISSUE THREAD

**Issue by LorhanSohaky** [timarney/react-app-rewired#447] opened 2020-03-10 14:40 UTC
File: `config/env.js`
```javascript
const stringified = {
    '__DEV__': process.env.NODE_ENV_ROOT === 'development' || process.env.NODE_ENV !== 'production',
    'process.env': Object.keys(raw).reduce((env, key) => {
      env[key] = JSON.stringify(raw[key])
      return env
    }, {})
  }
```

**Comment by timarney** [comment] 2020-04-20 10:54
I believe that's still getting set here
```
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/start.js#L13 
```

 I could be wrong as I haven't looked at any of the more recent version(s) of react-scripts

Closing this as no one has picked it up and it's not a bug.

**Closed by timarney** 2020-04-20 10:54 UTC

**Comment by LorhanSohaky** [comment] 2020-04-20 22:22
Thanks!!!!
